version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expose backend on port 8080
      - "3000:80"    # Expose frontend on port 3000 (nginx serves the built React app)
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tpdb
      SPRING_DATASOURCE_USERNAME: imane
      SPRING_DATASOURCE_PASSWORD:
      # Add any other necessary Spring environment variables here

  db:
    image: postgres:14  # Use a specific version of PostgreSQL
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    environment:
      POSTGRES_DB: tpdb
      POSTGRES_USER: imane
      POSTGRES_PASSWORD:
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - app-network

volumes:
  postgres_data:  # Named volume for PostgreSQL data

networks:
  app-network:
    driver: bridge